name: push

permissions: read-all

on: [push, pull_request]

env:
  GO_VERSION: "1.21.0"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/checkout@v3

      - name: Install ImageMagick
        run: sudo apt install -y imagemagick

      - uses: golangci/golangci-lint-action@v3
        with:
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout 5m
          version: latest

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/checkout@v3

      - name: Install ImageMagick
        run: sudo apt install -y imagemagick

      - name: Test
        run: go test -v ./...
