name: push

permissions: read-all

on: [push, pull_request]

env:
  GO_VERSION: "1.20.3"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
          stable: false

      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout 5m

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
          stable: false

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...
